#!/usr/bin/env bash

if [[ -s "$HOME/.rvm/environments/ruby-1.9.2-p0@global" ]] ; then
  \. "$HOME/.rvm/environments/ruby-1.9.2-p0@global"
  exec irb "$@"
else
  echo "ERROR: Missing RVM environment file: '$HOME/.rvm/environments/ruby-1.9.2-p0@global'"
  exit 1
fi
  