#!/usr/bin/env bash

if [[ -s "$HOME/.rvm/environments/ruby-1.9.2-head" ]] ; then
  \. "$HOME/.rvm/environments/ruby-1.9.2-head"
  exec erb "$@"
else
  echo "ERROR: Missing RVM environment file: '$HOME/.rvm/environments/ruby-1.9.2-head'"
  exit 1
fi
  