#!/usr/bin/env bash

if [[ -s "$HOME/.rvm/environments/ruby-1.8.7-p302@global" ]] ; then
  \. "$HOME/.rvm/environments/ruby-1.8.7-p302@global"
  exec rdoc "$@"
else
  echo "ERROR: Missing RVM environment file: '$HOME/.rvm/environments/ruby-1.8.7-p302@global'"
  exit 1
fi
  