#!/usr/bin/env bash

if [[ -s "$HOME/.rvm/environments/ruby-1.9.2-head@global" ]] ; then
  \. "$HOME/.rvm/environments/ruby-1.9.2-head@global"
  exec testrb "$@"
else
  echo "ERROR: Missing RVM environment file: '$HOME/.rvm/environments/ruby-1.9.2-head@global'"
  exit 1
fi
  