#!/usr/bin/env bash

if [[ -s "$HOME/.rvm/environments/ruby-1.8.7-p302@rails2tutorial" ]] ; then
  \. "$HOME/.rvm/environments/ruby-1.8.7-p302@rails2tutorial"
  exec rake "$@"
else
  echo "ERROR: Missing RVM environment file: '$HOME/.rvm/environments/ruby-1.8.7-p302@rails2tutorial'"
  exit 1
fi
  